### ISSUE TITLE
Specify what godot versions are supported in the README

### ISSUE THREAD

**Issue by RcubDev** [nikoladevelops/godot-blast-bullets-2d#2]
Hi there, I am looking at your plugin and its unclear to me what version of godot it is intended for. Could the readme be updated to make it more clear?

**Comment by nikoladevelops** [comment]
On `Releases`, I have stated that the plugin is for Godot 4.1 and Godot 4.2 (also visible in the repository tags). I've now updated the README file too as you suggested, so it's as clear as possible.
